### ISSUE TITLE
Find all uses of direct `sbot` access in packages

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#104]
To support _multiple server implementations_, packages should preferably use the `ssb.*` high-level APIs instead of direct `ssb.sbot.*` access because the later can end up providing an API that is only present on a single server implementation.

To better understand the refactoring needs to remove direct `sbot` access, we need to find out where this access happens.

* [x] find all packages that access `sbot` directly.
* [ ] find all packages that use some NPM dependency that access `sbot` directly.

**Comment by soapdog** [comment]
searching for `sbot.` in the `src/packages/` folder found 121 files accessing it directly... oh boi, this will be a huge task.

**Comment by cryptix** [comment]
@happy0 did something very similar with his chess app to make it work in browser/db2. Maybe you should compare some notes? :)

**Comment by soapdog** [comment]
Only 17 matches left. They are all pipelines using pull streams.

**Comment by soapdog** [comment]
🔥  This issue is on FAYAH! 🔥 

Almost done with removing direct sbot usage from packages. This is the first step in allowing Patchfox to work with other backends.

**Comment by soapdog** [comment]
The remaining four files using `sbot` directly are doing it in _pull stream pipelines_ that are bespoke to their needs. I don't feel we should abstract them into some function in `ssb.*`, instead the plan will be implementing #106 and provide a mechanism for package developers to detect and branch their code depending on what kind of backend is running.

**Comment by soapdog** [comment]
The packages making direct pull-stream calls are:

* Books
* Calendar
* Zine
* Contacts

**Comment by soapdog** [comment]
I suspect this is done.
