### ISSUE TITLE
Abililty to browse posts from people I follow

### ISSUE THREAD

**Issue by nsantini** [soapdog/patchfox#123]
Planetary has a Discover feature where you can see posts of the "wider" network, but the "feed" feature only shows posts by people you follow.
I think this kind of features would be useful for Patchfox. I think Manyverse has something like this on its roadmap too.

**Comment by soapdog** [comment]
This has been implemented. You can customise what messages you see based on your relationship graph.

![image](https://user-images.githubusercontent.com/23247/189445705-843150ff-6c21-4a09-a72b-bccad2a6c93a.png)
