### ISSUE TITLE
can't open setup page / no config

### ISSUE THREAD

**Issue by cryptix** [soapdog/patchfox#13]
After #12 I got this:

![patchfox1](https://user-images.githubusercontent.com/111202/50373399-f7d01a80-05de-11e9-986b-5f448bddd0fe.png)

but when I click any of the links I get this permission error:

```
Access to the file was denied

The file at moz-extension://1d17aeee-5411-455d-a050-8858ba5ccbf8/setup is not readable.

    It may have been removed, moved, or file permissions may be preventing access.

[Try Again]
```
**EDIT:** Workaround: https://github.com/soapdog/patchfox/issues/13#issuecomment-449562716

![patchfox1 5](https://user-images.githubusercontent.com/111202/50373398-f7d01a80-05de-11e9-9e97-a81f43ab84fa.png)

I peeked into the dev console of the plugin and the browser console. What stood out to me was this:  `error in silent test TypeError: "net.connect is not a function"` ~~I know this error from back when I used `patchlite`. When it wasn't correctly browserifed, there were remains of nodejs env code that just wouldn't work. But maybe this is just the missing config/ and thus no keys and  `remote: ws://..`?~~ Anyhow: How should I initialize the config?

**EDIT** yup - missing remote. workaround: craft a config to localStorage key `config` or overwrite src/packages/setup/model.js.

![patchfox2](https://user-images.githubusercontent.com/111202/50373400-f7d01a80-05de-11e9-9001-8de4a370747f.png)
![patchfox3](https://user-images.githubusercontent.com/111202/50373401-f7d01a80-05de-11e9-89a9-fd751cf2f76a.png)

**Comment by cryptix** [comment]
I found https://github.com/soapdog/patchfox/blob/master/src/packages/setup/model.js#L6

and will see if I can make it work.

btw: did you know that muxrpc supports getting the manifest from the server as part of the setup? this might remove a good chunk of the `require('..path/to/manifest')` juggling.

**Comment by cryptix** [comment]
Okay.. the _gotcha_ about the permissions was that the `[Public] [Profile]    [Setup]` links are sometimes pointing at `[web-ext-uuid]/profile` instead of `[web-ext-uuid]/index.html#/profile`. Using the later manually works but I still get `no sbot`

**Comment by cryptix** [comment]
partial :tada: !! had a typo in my `remote: ws://...` 

It _loads_ but does not display anything because of this error: `TypeError: "_timeago.default is not a function"`
![patchfox-timeago](https://user-images.githubusercontent.com/111202/50373666-a4f86200-05e2-11e9-8b8a-30b4793a3f78.png)

but even seeing the queries messages already feels great!!!

I tried to find out what that is but it seems to be generated code... :cold_sweat: 

```
patchfox $ git grep timeago.default
debug/src.a2b27638.js:    const timeagoInstance = (0, _timeago.default)();
debug/src.a2b27638.js:    const timeagoInstance = (0, _timeago.default)();
dist/src.a2b27638.js:    var timeagoInstance = (0, _timeago.default)();
```

**Comment by soapdog** [comment]
This has been fixed in the current version. Thanks for all the help!

**Comment by rmdes** [comment]
That's what I did, 

First I misread the instructions, thinking it would work with Firefox Stable (why is the extension even published if it only works with Firefox dev is confusing in my opinion, just honest feedback :) 

- installed Firefox dev edition
- Enabled Temporary Extensions for This Firefox dev with manifest.json in /dist
- Installed the extension
- Ran npm ssb-server to have .ssb/secrets generated
- back to Firefox dev, click on settings = blank page
Other patchfox actions (any beside settings actually) give me a 404 error

It's like my Firefox dev can't read
.ssb/secrets?

I'm on Manjaro/arch, kernel 5.10

**Comment by soapdog** [comment]
@rmdes I could reproduce here. I'll issue a patch tomorrow.

Oh, and the add-on is supposed to work with Firefox Stable, you don't need dev. I'll reach out with the update as soon as I get it working.

**Comment by soapdog** [comment]
Related to #127 and being tracked on #130.

**Comment by soapdog** [comment]
@rmdes this should be fixed in the latest commit. I've issued updates to all stores but they take some time to process.

**Comment by rmdes** [comment]
Alright will test and report back, thanks a lot for all your hard work!

**Comment by rmdes** [comment]
Working smooth !! 👍🏽 

![image](https://user-images.githubusercontent.com/12155003/155344478-046d1e2b-0882-4170-af21-0f8c8644d4db.png)
