### ISSUE TITLE
issue to delete identity

### ISSUE THREAD

**Issue by rmdes** [soapdog/patchfox#135]
So I have added a type of identity that patchfox can't work with (my manyverse ID)

I'm trying to remove it, but no success, the button does not do anything. 

Is there a config file I can manually edit to remove this second identity ? 

npm ssb-server running : 
![image](https://user-images.githubusercontent.com/12155003/155365062-69272610-0e5f-4d76-ad47-1ab661ea70bc.png)

**Comment by soapdog** [comment]
If you go to settings -> identities and remotes, you can remove an identity using the _remove_ button.

I just tested here and it worked.
