### ISSUE TITLE
Issue when blocking spam

### ISSUE THREAD

**Issue by rmdes** [soapdog/patchfox#136]
![image](https://user-images.githubusercontent.com/12155003/155366488-39d9e293-56b6-4a6e-9503-895d91852f90.png)

- so this is from the "Public" feed, when I try to block that russian bot, I see this popping up in the terminal running the server : 
![image](https://user-images.githubusercontent.com/12155003/155367220-f591e5f5-b2f5-42d3-94fc-1d716fd01016.png)

![image](https://user-images.githubusercontent.com/12155003/155366664-2e002db1-e809-4e92-8913-0d7343fb7b90.png)

Each time I click block/unblock it creates this block of error

this is the kind of post I don't want to see on ssb : (russian bot sharing DVD's from RSS ????)
ssb:message/sha256/mNU1xkvCm4xh9j8AfMMnWOl6i-BW5ieJPDCQsqVUd48=

**Comment by soapdog** [comment]
Sorry, I can't reproduce this error. It is appearing to work fine here.

That is a strange error that doesn't appear to be related to blocking. From the _trace message_ it appears to be related to blobs. What server are you running?
