### ISSUE TITLE
View full thread: URIError: malformed URI sequence

### ISSUE THREAD

**Issue by cryptix** [soapdog/patchfox#14]
With the two patches from #12 I can now browse /public but when I try to click `[View full profile]` it doesn't do anything but print this error:

```
URIError: malformed URI sequence src.a2b27638.js:1925:54

resolveRoute moz-extension://25782a02-b75f-4838-a8d0-f3db07a51f91/src.a2b27638.js:1925 
RegExpGetFunctionalReplacement self-hosted:4956
RegExpLocalReplaceOptFunc self-hosted:5253
Symbol.replace self-hosted:4851
replace self-hosted:5590
resolveRoute moz-extension://25782a02-b75f-4838-a8d0-f3db07a51f91/src.a2b27638.js:1920
asyncId moz-extension://25782a02-b75f-4838-a8d0-f3db07a51f91/src.a2b27638.js:1833 
```

`copy link location` gave me this: `moz-extension://25782a02-b75f-4838-a8d0-f3db07a51f91/index.html#/thread/%8qyJ1ywzjoi8ENkCNFRSTqC0Td8VX0nC5sZ3EHfyFcM=.sha256`

**Comment by cryptix** [comment]
workaround: use the `ssb:%...` style permalinks

**Comment by soapdog** [comment]
Thanks for the help! This still affects some edge cases but I am trying to filter them all out. The browser is really angry with `%` and `+` in our hashes. I'm URI encoding the hashes when I can but sometimes they come as raw HTML in posts and then it is tricky. I am closing this issue as the add-on has been completely rewritten and view full profile works for now.
