### ISSUE TITLE
gulp: no gulpfile found

### ISSUE THREAD

**Issue by radfish** [soapdog/patchfox#18]
```
$ gulp 
[18:53:55] No gulpfile found

$ gulp --version
[18:55:27] CLI version 2.0.0
[18:55:27] Local version 4.0.0
```

Is the readme out of date?

**Comment by edrex** [comment]
also no package.json for `npm install` step.

**Comment by soapdog** [comment]
Yes, README is out of date, I've been rewriting everything. This is now a build-less project. The JS on the repo is what is delivered and executed. No more need for NPM and build steps. I'm gonna update the readme now.

**Comment by soapdog** [comment]
I'm closing this as it is no longer applicable. The project changed a lot, multiple times, since this issue was posted. Thanks again for helping. The current readme reflects the current svelte based instalation. All that is needed is NPM (for development purposes only).
