### ISSUE TITLE
Support site on moz add-ons 404s

### ISSUE THREAD

**Issue by olizilla** [soapdog/patchfox#26]
Just an old link on the old web linking to a location that no longer exists https://github.com/ssbc/patchfox/issues

**Comment by olizilla** [comment]
<img width="263" alt="Screenshot 2019-06-12 at 09 43 44" src="https://user-images.githubusercontent.com/58871/59336506-9cadf380-8cf6-11e9-81bd-ae95d4941605.png">

**Comment by soapdog** [comment]
argh, pointed it at the wrong location. I've just fixed it! Thanks for spotting that @olizilla
