### ISSUE TITLE
Lost connection warning while trying to post for the first time

### ISSUE THREAD

**Issue by olizilla** [soapdog/patchfox#28]
I got this the first time i posted. I hit preview, then hit go back to edit a typo, then hit post, then the warning showed up... patchwork was running all the while.

<img width="1440" alt="Screenshot 2019-06-12 at 09 39 49" src="https://user-images.githubusercontent.com/58871/59336597-c2d39380-8cf6-11e9-9074-5efa4ff8dd0d.png">

**Comment by soapdog** [comment]
@olizilla I'm trying to come with a way to reconnect when this happens. By the way did it refresh on its own like the toast message says? It should have refreshed and kept your content.

This is related to #29

**Comment by olizilla** [comment]
Alas no, it stayed there, so I grabbed my text and hit reload. It worked fine the second time round.

**Comment by soapdog** [comment]
This is fixed for normal connection breaks. It will detect the broken connection and ask if you want to reconnect and try posting again.
