### ISSUE TITLE
Other extensions can't run on Patchfox pages

### ISSUE THREAD

**Issue by cinnamon-bun** [soapdog/patchfox#32]
Firefox won't run other extensions on Patchfox pages.  (For example: Vimperator, Stylus)

This is probably because they're `moz-extension://` pages?  Is there any workaround to this?

**Comment by soapdog** [comment]
@cinnamon-bun I don't know if that is possible. I'm gonna check with moz.

**Comment by cinnamon-bun** [comment]
Are extensions allowed to run a localhost webserver?  That might be a workaround.

(The security of that is hard to get right though, to keep any page on the web from sending requests to your localhost server)

**Comment by soapdog** [comment]
@cinnamon-bun unfortunately WebExtensions can't run webservers, they don't even have access to sockets or the filesystem.

**Comment by soapdog** [comment]
I can't fix this, it is a limitation on webextensions. There are ways to do it but it requires all developers involved cooperating. It is not transparent.
