### ISSUE TITLE
The setting `Messages per page` is not considering the message types

### ISSUE THREAD

**Issue by romuloalves** [soapdog/patchfox#36]
The setting `Messages per page` is set to `10` but my public feed shows just 3 messages because I'm filtering just the messages with type `Blog`, `Channel`, `Contact` and `Posts`.

If all message types are on (to be visible) the feed shows the right amount of messages.

**Comment by soapdog** [comment]
@romuloalves which version of the extension you're using? You can see this on the Firefox Add-ons manager.

**Comment by romuloalves** [comment]
@soapdog 
**The version is 2019.6.2.**

My settings:
<img width="881" alt="image" src="https://user-images.githubusercontent.com/3952526/60735012-2c2a7900-9f28-11e9-8490-39cdb9f1b290.png">

I couldn't take a fullpage screenshot to show you, but my public feed contains 6 items.
With all message types enabled, the feed is showing the 10 items.

**Comment by soapdog** [comment]
Will double check @romuloalves, this shouldn't really happen.

**Comment by soapdog** [comment]
@romuloalves I've fixed it. It will go into the next release, I'm doing some other fixes.
