### ISSUE TITLE
DAT pinning with Hashbase

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#50]
Ideally when a user attach a file using DAT, we pin the file to Hashbase. I don't have a clue how to do that.

**Comment by RangerMauve** [comment]
Here's the library that can talk to hashbase. https://github.com/beakerbrowser/dat-pinning-service-client

Ideally people should create their own accounts on it and then log in.

The UI should have a `service URL`, `username` and `password` field.

Then you can `log into` the service and get a token that you can use with the service URL for doing the various operations.

The reason for having the service URL is that people might want to self-host their own pinning service or have something like `dat-store` running locally.

**Comment by RangerMauve** [comment]
cc @pfrazee: Would a PR for the CORS headers be welcome since this seems to be something people want to work with but can't?

**Comment by pfrazee** [comment]
There's an issue and PR ongoing https://github.com/beakerbrowser/hashbase/issues/118

**Comment by soapdog** [comment]
I've removed both DAT and IPFS features from the current branch as I refactored it a lot. I'll revisit those features soon and taking all of this into account.
