### ISSUE TITLE
implement `ContentWarning` spec v3 

### ISSUE THREAD

**Issue by soapdog** [soapdog/patchfox#51]
Implement the _strict set_ or rules (sugestions?) in v3 of the Content Warning spec that was detailed in the following images:

![c1](https://user-images.githubusercontent.com/23247/63358799-8c07a280-c363-11e9-9f71-c15b7080820a.png)

![c2](https://user-images.githubusercontent.com/23247/63358807-8f029300-c363-11e9-86e7-92f92c58b126.png)

![c3](https://user-images.githubusercontent.com/23247/63358815-93c74700-c363-11e9-8ff6-25626133794f.png)

Message: [%ldtPAbOKmOj8UkF+Xw7VTgXefg3W4BAluLDs4Lv53mk=.sha256](ssb:%ldtPAbOKmOj8UkF+Xw7VTgXefg3W4BAluLDs4Lv53mk=.sha256)

**Comment by soapdog** [comment]
Patchfox doesn't support gatherings yet so I'll implement this for messages of type `post` and `blog`.

**Comment by cinnamon-bun** [comment]
The spec is also here: https://github.com/ssbc/ssb-spec-drafts/blob/ssb-app-content-warning/drafts/draft-ssb-app-content-warning/00/draft-ssb-app-content-warning-00.md
...with some extra context and ideas for settings, etc

**Comment by soapdog** [comment]
I think that the current CW spec is OK for now. I'll revisit it if we start having needs which are not yet covered. Thanks a lot for the hard work on this @cinnamon-bun
