### ISSUE TITLE
Broken link to ssb-server

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/patchfox#62]
Hey @soapdog :-)

I just installed this extension and found the [guide](https://github.com/soapdog/patchfox/blob/ca50284d9813095171b2111638d6e53559109e34/docs/guide.md) having a broken link to https://www.npmjs.com/packages/ssb-server

It should be https://www.npmjs.com/package/ssb-server (singular).

**Comment by soapdog** [comment]
irgh!!! Gonna fix that ASAP! Thanks for spotting it.
