### ISSUE TITLE
No new messages after following user

### ISSUE THREAD

**Issue by Ryuno-Ki** [soapdog/patchfox#63]
This is my first time using SSB.

I followed [an user I found online](http://andregarzia.com/about.html) and hit „Load more” after switching the „following” toggle to on. Then this appeared:

![first-start](https://user-images.githubusercontent.com/3097194/68153757-63487f80-ff46-11e9-9516-6e0487a4f138.png)

Is there some smarter way to handle it? It appears to me to be an „empty screen” UX problem.

**Comment by soapdog** [comment]
Unfortunately there are many moving parts and I am yet to cover all the potential errors. That screen allows a person to jump straight to issues here and at least tell me about it which then allows me to try to fix it.

I will try to see if I can see there why this has happened. Just be aware that the error manifesting there might be a side-effect of another problem. Somehow the `ssb-ws` connection between _sbot_ (aka `ssb-server`) and patchfox has been disconnecting after sometime when it shouldn't do so causing the _pull streams_ being used to close unexpectedly. The solution to that error is apparently use the undocumented `pull-reconnect` which I haven't yet discovered how to use.

I will work on this and try to see if I can make that specific case not happen again. The screen you're seeing is the last resort error screen. If it is something that patchfox can't handle it shows that which is IMHO better than just crashing.

**Comment by soapdog** [comment]
Also it is important to notice that between you following and messages arriving it will take a long time. You need to fetch and index these messages. This is not like an Instant Messenger kind of situation that you just ask "give me the last 10 messages for user X", it is a bit more involved than that and it takes time.

What I suspect happened is that you clicked follow but your db still didn't had any message for my user in there and thus the `lastMsgs` variable was empty.

I'm going to add an empty messages check there. Thanks a lot for spotting it @Ryuno-Ki

**Comment by Ryuno-Ki** [comment]
Sounds like a very defensive coding style...
Which can be a good thing.
