### ISSUE TITLE
French translation & blob question

### ISSUE THREAD

**Issue by zicmama** [soapdog/patchfox#68]
Hi,
New to ssb universe, I really love it!!! I am also intensively using ipfs...
I am willing to help.

- First making translations (please could you tell me how to provide it?)
- Second: lbob is the solution to sotre & exchange large amount of data.
I am working on a file container along with #g1 (https://duniter.org) contracts stored in ipfs... It is really looking and almost working like blob's. I am still looking on how to use it as a sidechain for ssb messages...

**Comment by soapdog** [comment]
hello @zicmama,

Thanks for the offer of help. At the moment Patchfox is moving in many different directions and it is not uncommon for me to rewrite all of it every couple months. I don't want to encourage contributions and then throw away patches that were painfully built by wonderful people when I decide to throw away the source code and rebuild. Be aware that has been about seven rewrites so far. I hope you understand that I love contributions and contributors but this project is more of a laboratory for my own explorations and I like burning it down.

A project that is quite similar but that is way more stable and has a wonderful team contributing to it and could benefit a lot from your help is [Oasis](http://github.com/fraction/oasis). I bet they could use a French translation and more help.

---

As for the blob question, in another version Patchfox had support for both DAT and IPFS attachments. I plan to re-add these in the near future. Still, the idea of an offline-first platform is kinda broken when we add these sidechains as they don't work if the internet is unavailable.

**Comment by zicmama** [comment]
> in another version Patchfox had support for both DAT and IPFS attachments
We really have to share our experience. As I am mixing a crypto coin with file usage, it makes an "economic model" for ipfs swarm storage.

> they don't work if the internet is unavailable
What do you mean? My ipfs swam is working as long an IP connection (at least LAN) is available...
In fact this could be a complete fat protocol layer for Internet itself

I manage to extend my ipfs swarm by sending through ssh the swarm.key to new friendly nodes.
Now each node runs ipfs + ssb, I wish to use scuttlebut to make that key exchange through friends links and private message...

**Comment by soapdog** [comment]
> What do you mean? My ipfs swam is working as long an IP connection (at least LAN) is available...
In fact this could be a complete fat protocol layer for Internet itself

I'm mistaken then. I suspected that IPFS had to reach a supernode or something similar to reach their DHT. Sorry.

**Comment by zicmama** [comment]
You are right, ipfs calls "supernode/Pub" a "bootstrap", it could be any LAN or WAN IP (as long at it is routable). Ass ssb does, ipfs is not taking care of that...

What is important, is that, at least one of these special 24/24 node runs a task scheduler to maintain a fresh ipns dht index and be ready to serve fresh data to other nodes

In my swarm, a simple 1 mn cron maintains a fifo about all ipns index then refresh (ipfs get) and republish (12h amx) current status regularly. 

All distributed system have that DHT coherence problem... gossip protocol is maintaining it. So ssb, ipfs even cjdns are very closed in their fonctions and features, but with different interaction level...
I love to mix them ;)
