### ISSUE TITLE
manifest is not defined

### ISSUE THREAD

**Issue by vincentux** [soapdog/patchfox#69]
After I entered my secret file,
I have the following message: 
`ReferenceError: manifest is not defined`

- Xubuntu
- Firefox 72.0.1
- Patchfox 2020.2.1

**Comment by cryptix** [comment]
I also ran into this yesterday, using the latest version of patchwork.

The manifest.json has a `manifest: async` though and I can run `sbotcli call manifest` to get it...? 😬🤷‍♂️

cc @christianbundy since I think this is used in oasis, too?

**Comment by cryptix** [comment]
Okay, this is not actually about the RPC command. I used a local dev build to get the sourcemap and tracked it down to here:

https://github.com/soapdog/patchfox/blob/614d19154a964f62f7cd39a70ea8e37c4e33f447/src/packages/settings/IdentityAndConnection.svelte#L12

I don't see a (re-)definiton of `manifest` anywhere in that file. I think it was a configuration value in a previous version?

**Comment by cryptix** [comment]
okay, i also found `src/core/platforms/ssb/manifest.js` so I think this is an relict that can be removed altogetehr.

**Comment by BorisPAING** [comment]
Same problem here.

Windows 7
Firefox 72.0.2

**Comment by soapdog** [comment]
I have a fixed version here, will release today.

**Comment by soapdog** [comment]
this has been fixed.
