### ISSUE TITLE
Non-square avatars show up in wrong aspect ratio

### ISSUE THREAD

**Issue by aadilayub** [soapdog/patchfox#74]
People who have profile pictures that are not square, their avatars show squished versions of their profile picture.

Example:

![image](https://user-images.githubusercontent.com/31581044/76825572-28cbe900-683c-11ea-9817-78d2e4c70d67.png)

![image](https://user-images.githubusercontent.com/31581044/76825540-181b7300-683c-11ea-93aa-ae514874ff31.png)

Hope you don't mind me using screenshots of your ssb profile here @christianbundy

**Comment by Ryuno-Ki** [comment]
Hm, I wonder, whether `object-fit` could [help](https://24ways.org/2019/flexible-captioned-slanted-images/) here?

More common I see modals allowing to crop a square from an uploaded image.

**Comment by christianbundy** [comment]
Yep, `object-fit: cover` does what we want. In the future I'll upload square avatars but I think it's wise to expect lots of funky image sizes from other clients.
