### ISSUE TITLE
Large images don't fit in post container

### ISSUE THREAD

**Issue by aadilayub** [soapdog/patchfox#78]
![image](https://user-images.githubusercontent.com/31581044/85936597-c643b800-b915-11ea-857f-62fd2904b7b7.png)

Adding `width: 100%` to `.card-body img` seems to fix it:

![image](https://user-images.githubusercontent.com/31581044/85936651-24709b00-b916-11ea-9d0d-91ad84245db4.png)

**Comment by soapdog** [comment]
fixed some time ago, don't remember when.
