### ISSUE TITLE
Connecting to a remote SSB-Server

### ISSUE THREAD

**Issue by JonTheNiceGuy** [soapdog/patchfox#80]
It'd be really handy if it were possible to connect from Firefox on my machine to a ssb-server running on another machine in the network :)

This would mean I wouldn't need to keep my multi-GB profile files on my local laptop!

**Comment by soapdog** [comment]
@JonTheNiceGuy you can do that by altering the remote in _settings_. I suspect I might have some hardcoded URLs for blob retrieval though. Need to check.
