### ISSUE TITLE
columnSize setting has no effect

### ISSUE THREAD

**Issue by gtim** [soapdog/patchfox#93]
The columnSize ("short/long" column) setting seems to have no effect.

I'm thinking the setting should either be removed, or taken into account. What would be best @soapdog ? I'd be happy to try submitting a pull request for either.

**Comment by soapdog** [comment]
@gtim that is true. It is a leftover from past versions where the _window manager_ was more flexible. I'm gonna do a major rework of that part of the _display preferences_ for the next version. Better not to send a PR because I'm gonna kick the can on those files shortly.

**Comment by gtim** [comment]
Alright, thanks for swift response!
